---
name: "Publish Peertube"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]
    paths: [".github/workflows/publish-containers.yaml"]

jobs:
  publish-containers:
    name: Publish Containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: "${{ secrets.DEPLOY_USER }}"
          password: "${{ secrets.DEPLOY_TOKEN }}"

      - name: Download latest release
        id: latest-release
        uses: robinraju/release-downloader@efa4cd07bd0195e6cc65e9e30c251b49ce4d3e51 # v1.8
        with:
          repository: Chocobozzz/PeerTube
          latest: true
          fileName: "*.zip"
          extract: false

      - name: Extract Peertube release
        run: |
          unzip peertube-${{steps.latest-release.outputs.tag_name}}.zip
          rm peertube-${{steps.latest-release.outputs.tag_name}}.zip

      - name: Build and push Docker image
        uses: docker/buildx-build-action@v1
        with:
          context: .
          dockerfile: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/jahanson/peertube-server:${{steps.latest-release.outputs.tag_name}}