---
name: "Publish Peertube"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]
    paths: [".github/workflows/publish-containers.yaml"]

jobs:
  setup-containers:
    name: Setup Containers
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download latest release
        uses: robinraju/release-downloader@efa4cd07bd0195e6cc65e9e30c251b49ce4d3e51 # v1.8
        with:
          repository: Chocobozzz/PeerTube
          latest: true
          fileName: "*.zip"
          extract: true
  publish-containers:
    name: Publish Containers
    runs-on: ubuntu-latest
    needs: ["setup-containers"]
    steps:
      - name: Output tag name
        env:
          TAG_NAME: ${{needs.setup-containers.outputs.tag_name}}
        run: |
          echo "Tag name: $TAG_NAME"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ github.workspace }}/peertube-${{steps.setup-containers.outputs.tag_name}}/dist
          dockerfile: ${{ github.workspace }}/Dockerfile
          push: true
          tags: peertube-server:${{steps.setup-containers.outputs.tag_name}}